services:
  icbc-catcher:
    build: .
    container_name: icbc-road-test-catcher
    env_file: .env
    # * Create a .env file in the same directory and add the following environment variables:
    # * or you can uncomment the environment section below and add the variables directly.
    # environment:
    #   - TZ=America/Vancouver
    #   - USER_LAST_NAME=YourLastName
    #   - USER_LICENSE_NUMBER=1234567
    #   - USER_KEYWORD=your_keyword_here
    #   - USER_GMAIL=your.email@gmail.com
    #   - USER_GMAIL_APP_PASSWORD=your_16_character_app_password
    #   - DESIRED_DATE_START=2025-06-24
    #   - DESIRED_DATE_END=2025-06-30
    #   - APPROVAL_TIMEOUT=300
    #   - ACTION=book # or "look"
